### ISSUE TITLE
Add Kitty image protocol support

### ISSUE THREAD

**Issue by ctrlcctrlv** [simoncozens/font-engineering#5]
I might try to contribute this some day. Kitty here refers to kovidgoyal/kitty

**Comment by ctrlcctrlv** [comment]
Oh actually this is so simple to add I already got it working. PR incoming

**Comment by alerque** [comment]
How about Alacritty?

**Comment by ctrlcctrlv** [comment]
@alerque [I personally am not a fan](https://gist.github.com/ctrlcctrlv/978b3ee4f55d4b4ec415a985e01cb1c9). But feel free to use whatever you like. If you use Kitty, you get the benefit of my OpenType patch (kovidgoyal/kitty#2248) and background image patch (kovidgoyal/kitty#2326), fyi. :-)
