### ISSUE TITLE
Name conflict with fontParts fontShell

### ISSUE THREAD

**Issue by benkiel** [simoncozens/font-engineering#7]
I know this was raised on twitter a while ago, but that was likely lost. This is your package of tools, so you are of course free to do whatever you want, but there is a naming confusion between this `fontShell` and `fontShell` from `fontParts`.

**Comment by simoncozens** [comment]
Ah, good point. OK, so there is a clash, but I wonder if it actually matters - one is an executable and one is a library. If people are referring to them in conversation I can see that it might get confusing, but I can't see any confusion in use.

**Comment by alerque** [comment]
I think the thing in `fontParts` that is a library also comes with a sample CIL implementation, so yes there seems to be a clash.

**Comment by benkiel** [comment]
Two things: they are both based in python, and work in a python environment, so it isn't quite a clash, but confusing. Second, the fontShell name has been around and is known to Simon, so I'm confused as to why the name clash in the first place (yes, I am being grumpy, I know!).

Both those things said, yes, I don't know if there will be a lot of overlap/confusion in practice, and I'm not going to get in the way of a nice package of tools, so I'll leave this up to Simon and close this issue.
