### ISSUE TITLE
glypsh2svg --remove-overlaps

### ISSUE THREAD

**Issue by davelab6** [simoncozens/font-engineering#8]
https://github.com/simoncozens/font-engineering/blob/master/glyphs2svg.py doesn't remove overlaps, which causes some SVGs output to be unexpected. 

So I'd like to request an argument that includes the typical https://github.com/fonttools/skia-pathops method to resolve that, and make the SVGs output more like instantiated fonts.

Example Glyphs source file: www.github.com/Ancymonic/Signika/blob/master/sources/Signika-MM.glyphs 

VF TTF: www.github.com/Ancymonic/Signika/blob/master/fonts/signikavf/Signika[NEGA,wght].ttf

**Comment by anthrotype** [comment]
svg paths can have overlaps, the default fill-rule (which fontTools svgPathPen does not override) is "nonzero", like the one used for TrueType fonts, so overlaps should just work.
Can you paste a screenshot and with name of the glyph that reproduces this?

**Comment by simoncozens** [comment]
Confirmed with Signika's ico.escalator. This is not exactly an overlaps issue, but one where:

* in TTF, we expect clockwise paths to fill black, and anticlockwise paths to cut out counters.
* in glyphs2svg, we export each path as a separate `<path>` element and it necessarily fills black, regardless of the directions and winding numbers of paths around it.
